services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env:ro
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
volumes:
  mongodb_data: